image:
  tag: 372

additionalCatalogs:
  minio: |
    connector.name=hive-hadoop2
    hive.metastore.uri=thrift://my-hive-metastore:9083
    hive.s3.path-style-access=true
    hive.s3.endpoint=minio.trino.svc.cluster.local
    hive.s3.aws-access-key=BBT4GY4P028M7SMBC6Y9
    hive.s3.aws-secret-key=ZGkSh84bAtQfG69aZxP4HGHyACG0aMtkLb3XSwEG
    hive.non-managed-table-writes-enabled=true
    hive.s3select-pushdown.enabled=true
    hive.storage-format=ORC
    hive.allow-drop-table=true
    hive.s3.ssl.enabled=false


secretMounts:
  - name: redis-table-schema-volumn
    path: /etc/redis
    secretName: redis-table-definition
